[project]
name = 'Decentralized-Energy-Grid-Modernization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.infrastructure-upgrade]
path = 'contracts/infrastructure-upgrade.clar'
clarity_version = 2
epoch = 2.5

[contracts.smart-meter-integration]
path = 'contracts/smart-meter-integration.clar'
clarity_version = 2
epoch = 2.5

[contracts.utility-verification]
path = 'contracts/utility-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
